# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NodeCommunicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveRequestResourceUsage = channel.unary_unary(
                '/myservice.NodeCommunicationService/ReceiveRequestResourceUsage',
                request_serializer=service__pb2.UsageRequest.SerializeToString,
                response_deserializer=service__pb2.UsageResponse.FromString,
                _registered_method=True)
        self.ReceiveOkMessage = channel.unary_unary(
                '/myservice.NodeCommunicationService/ReceiveOkMessage',
                request_serializer=service__pb2.okMessage.SerializeToString,
                response_deserializer=service__pb2.UsageResponse.FromString,
                _registered_method=True)


class NodeCommunicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveRequestResourceUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveOkMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeCommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveRequestResourceUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveRequestResourceUsage,
                    request_deserializer=service__pb2.UsageRequest.FromString,
                    response_serializer=service__pb2.UsageResponse.SerializeToString,
            ),
            'ReceiveOkMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveOkMessage,
                    request_deserializer=service__pb2.okMessage.FromString,
                    response_serializer=service__pb2.UsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservice.NodeCommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myservice.NodeCommunicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeCommunicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveRequestResourceUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservice.NodeCommunicationService/ReceiveRequestResourceUsage',
            service__pb2.UsageRequest.SerializeToString,
            service__pb2.UsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveOkMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservice.NodeCommunicationService/ReceiveOkMessage',
            service__pb2.okMessage.SerializeToString,
            service__pb2.UsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
