# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import node_service_pb2 as node__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in node_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunElection = channel.unary_unary(
                '/node_service.Node/RunElection',
                request_serializer=node__service__pb2.NodeRequest.SerializeToString,
                response_deserializer=node__service__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.ReceiveCoordinatorMessage = channel.unary_unary(
                '/node_service.Node/ReceiveCoordinatorMessage',
                request_serializer=node__service__pb2.NodeRequest.SerializeToString,
                response_deserializer=node__service__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.GetCoordinatorStatus = channel.unary_unary(
                '/node_service.Node/GetCoordinatorStatus',
                request_serializer=node__service__pb2.NodeRequest.SerializeToString,
                response_deserializer=node__service__pb2.NodeResponse.FromString,
                _registered_method=True)


class NodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunElection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveCoordinatorMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoordinatorStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunElection': grpc.unary_unary_rpc_method_handler(
                    servicer.RunElection,
                    request_deserializer=node__service__pb2.NodeRequest.FromString,
                    response_serializer=node__service__pb2.NodeResponse.SerializeToString,
            ),
            'ReceiveCoordinatorMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveCoordinatorMessage,
                    request_deserializer=node__service__pb2.NodeRequest.FromString,
                    response_serializer=node__service__pb2.NodeResponse.SerializeToString,
            ),
            'GetCoordinatorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoordinatorStatus,
                    request_deserializer=node__service__pb2.NodeRequest.FromString,
                    response_serializer=node__service__pb2.NodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'node_service.Node', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('node_service.Node', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Node(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node_service.Node/RunElection',
            node__service__pb2.NodeRequest.SerializeToString,
            node__service__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveCoordinatorMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node_service.Node/ReceiveCoordinatorMessage',
            node__service__pb2.NodeRequest.SerializeToString,
            node__service__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoordinatorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node_service.Node/GetCoordinatorStatus',
            node__service__pb2.NodeRequest.SerializeToString,
            node__service__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
